### ISSUE TITLE
Wikilink is not work for .webp files

### ISSUE THREAD

**Issue by hyj0824** [Mara-Li/mkdocs-obsidian-links#10]
I use Material for Mkdocs. And it does well on .md .png .jpg files.

When I tried to insert an .webp image, the building log didn't show anything wrong, but the output site tells me that "xxx.webp is not found"

I have already confirmed that the problem is not caused by spaces in filename.

**Comment by hyj0824** [comment]
If it's necessary to use your template to avoid this?

**Comment by Mara-Li** [comment]
Hello,
I can't repro : 
![image](https://github.com/user-attachments/assets/819dd21e-efca-4220-a8b1-b0af5da1f6ab)

![image](https://github.com/user-attachments/assets/ec6cdb67-8ba7-4b36-88f6-3a9ad0e16fa8)

**Comment by hyj0824** [comment]
I found the reason. There's another plugin doing the same thing thus it breaks the right link. Only use ezlink and it turned out ok.
