### ISSUE TITLE
Expecting `[[./a/index]]` to return `<a href="a/"`, get `<a href="a/index"`

### ISSUE THREAD

**Issue by ooker777** [Mara-Li/mkdocs-obsidian-links#2]
With this `mkdocs.yml`:
```yaml
site_name: test
plugins:
  - ezlinks:
        wikilinks: true
```
And this folder structure:
```
docs/ 
├── index.md 
└── a/ 
    └── index.md
```
After the build we will have:
```
site/ 
├── index.html
└── a/ 
    └── index.html
```

If in `docs/index.md` you have this content:
```markdown
[[a/index]]
[[a/index.md]]
[[./a/index]]
[[./a/index.md]]
```
Then in `site/index.html` the html will be:
```html
| docs/index.md    | site/index.html                                    | Correct? |
| ---------------- | -------------------------------------------------- | -------- |
| [[a/index]]      | <a href="a/" title="a/index">a/index</a>           | ✔        |
| [[a/index.md]]   | <a href="a/" title="a/index.md">a/index.md</a>     | ✔        |
| [[./a/index]]    | <a href="a/index" title="./a/index">./a/index</a>  | ❌       |
| [[./a/index.md]] | <a href="a/" title="./a/index.md">./a/index.md</a> | ✔        |
```

At the same time Mkdocs will notice this:
```
INFO    -  Doc file 'index.md' contains an
           unrecognized relative link
           'a/index', it was left as is. Did  
           you mean 'a/index.md'?
```
Do you think all of them should all convert to `<a href="./a"` or even `<a href="./a/index.html"`?

**Comment by Mara-Li** [comment]
I will try to fix this. But the code of ezlinks is pretty difficult to understand.

**Comment by ooker777** [comment]
since we are only working with wikilinks, why don't you choose another mkdocs plugin that can handle wikilinks and be bug-free?

**Comment by Mara-Li** [comment]
1. Because they are not 
2. Because some of my other plugin relies on it

**Comment by ooker777** [comment]
What are those plugins?

**Comment by Mara-Li** [comment]
The javascripts relies on it for the not found & all things I do to it

**Comment by Mara-Li** [comment]
Should be fixed within the last version
