### ISSUE TITLE
Space is erronously added to filename in wikilink syntax

### ISSUE THREAD

**Issue by mofosyne** [Mara-Li/mkdocs-obsidian-links#5]
```
[[Democracy Analysis Project - Links | Links]] 
```

will look for `'../democracy-analysis-project---links-'` but was expecting `'../democracy-analysis-project---links'`.

Should be easy to deal with by trimming spaces before processing.

At the moment this is my workaround

```
[[Democracy Analysis Project - Links| Links]] 
```

**Comment by Mara-Li** [comment]
Well, it's not the official syntax for Obsidian wikilinks : https://help.obsidian.md/Linking+notes+and+files/Internal+links#Change+the+link+display+text

It wont be fixed for this plugin but, using mkdocs, it is easy to add an hook that will be fix the text before the building, by searching and removing extra space.
You can check [`on_files`](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Change+the+link+display+text) events.
